version: "3.8"
services:
  app:
    build: .
    container_name: python-app-cmd
    volumes:
      - .:/usr/src/app
    environment:
      - API_TOKEN=token
      - CHAT_ID=chat
    command: python run.py